using DataFrames, CSV

# ── PCAP / flow ingestion ─────────────────────────────────────────────────────
#
# Three input modes:
#   1. tshark CSV  — real PCAP exported with tshark -T fields
#   2. Generic CSV — any flow CSV with at least src_ip, dst_ip, bytes columns
#   3. Synthetic   — generated by synthesis.jl (used when no PCAP available)
#
# All modes produce the same internal flow DataFrame schema:
#   ts, src_id, dst_id, src_ip, dst_ip,
#   src_port, dst_port, protocol, packets, bytes, duration_ms
# ─────────────────────────────────────────────────────────────────────────────

# tshark command to export a PCAP to the expected CSV format:
#
#   tshark -r capture.pcap -T fields \
#     -e frame.number -e ip.src -e ip.dst \
#     -e tcp.srcport  -e tcp.dstport \
#     -e udp.srcport  -e udp.dstport \
#     -e ip.proto -e frame.len -e frame.time_relative \
#     -E header=y -E separator=, -E quote=d \
#     > capture_flows.csv
#
# Then pass the CSV path to read_tshark_csv().

"""
    read_tshark_csv(path) -> (flows::DataFrame, hosts::DataFrame)

Read a tshark-exported CSV and produce the internal flow + host tables.
tshark exports one row per packet; this function aggregates into flows
grouped by (src_ip, dst_ip, src_port, dst_port, protocol).

Expected tshark columns (flexible — missing columns get default values):
  frame.number, ip.src, ip.dst,
  tcp.srcport OR udp.srcport, tcp.dstport OR udp.dstport,
  ip.proto, frame.len, frame.time_relative
"""
function read_tshark_csv(path::String)::Tuple{DataFrame, DataFrame}
    raw = CSV.read(path, DataFrame; missingstring="", types=String)

    # normalize column names: strip quotes, lowercase
    rename!(raw, [replace(string(c), "\"" => "") => replace(string(c), "\"" => "") for c in names(raw)])

    src_col  = _find_col(raw, ["ip.src",  "src_ip",  "source"])
    dst_col  = _find_col(raw, ["ip.dst",  "dst_ip",  "destination"])
    len_col  = _find_col(raw, ["frame.len", "bytes", "length"])
    time_col = _find_col(raw, ["frame.time_relative", "ts", "time"])
    proto_col= _find_col(raw, ["ip.proto", "protocol", "proto"])
    sp_col   = _find_col(raw, ["tcp.srcport", "udp.srcport", "src_port"])
    dp_col   = _find_col(raw, ["tcp.dstport", "udp.dstport", "dst_port"])

    rows = []
    for r in eachrow(raw)
        sip = _str(r, src_col);  isempty(sip) && continue
        dip = _str(r, dst_col);  isempty(dip) && continue
        # skip non-IPv4 (broadcast, multicast, ARP)
        occursin(r"^\d+\.\d+\.\d+\.\d+$", sip) || continue
        occursin(r"^\d+\.\d+\.\d+\.\d+$", dip) || continue

        nb    = _int(r, len_col,   0)
        sp    = _int(r, sp_col,    0)
        dp    = _int(r, dp_col,    0)
        ts    = _float(r, time_col, 0.0)
        proto = _str(r, proto_col)
        proto = _normalize_proto(proto)

        push!(rows, (src_ip=sip, dst_ip=dip, src_port=sp, dst_port=dp,
                     protocol=proto, bytes=nb, ts_sec=ts))
    end
    isempty(rows) && error("No valid IPv4 flow rows found in $path")

    pkt_df = DataFrame(rows)

    # aggregate packets → flows (5-tuple key)
    grp = groupby(pkt_df, [:src_ip, :dst_ip, :src_port, :dst_port, :protocol])
    agg = combine(grp,
        nrow         => :packets,
        :bytes       => sum => :bytes,
        :ts_sec      => (x -> round(Int, minimum(x) * 1000)) => :ts,
        :ts_sec      => (x -> round(Int, (maximum(x) - minimum(x)) * 1000)) => :duration_ms
    )

    return _assign_host_ids(agg)
end

"""
    read_generic_csv(path) -> (flows::DataFrame, hosts::DataFrame)

Read a generic flow CSV. Flexible column detection — works with Zeek conn.log,
NetFlow CSV, or any export with src/dst IP columns.

Minimum required columns: src_ip (or ip.src), dst_ip (or ip.dst).
Optional: src_port, dst_port, protocol, bytes, packets, duration_ms.
"""
function read_generic_csv(path::String)::Tuple{DataFrame, DataFrame}
    raw = CSV.read(path, DataFrame; missingstring="")

    src_col  = _find_col(raw, ["src_ip","ip.src","source_ip","orig_h","src"])
    dst_col  = _find_col(raw, ["dst_ip","ip.dst","dest_ip","resp_h","dst","destination_ip"])
    sp_col   = _find_col(raw, ["src_port","sport","orig_p"])
    dp_col   = _find_col(raw, ["dst_port","dport","resp_p"])
    by_col   = _find_col(raw, ["bytes","orig_bytes","byte_count","total_bytes"])
    pk_col   = _find_col(raw, ["packets","pkt_count","orig_pkts"])
    pr_col   = _find_col(raw, ["protocol","proto","service"])
    du_col   = _find_col(raw, ["duration_ms","duration","conn_duration"])
    ts_col   = _find_col(raw, ["ts","timestamp","frame.time_relative","time"])

    isnothing(src_col) && error("Cannot find src_ip column in $path")
    isnothing(dst_col) && error("Cannot find dst_ip column in $path")

    rows = []
    for (t, r) in enumerate(eachrow(raw))
        sip = string(get(r, src_col, ""));  isempty(sip) && continue
        dip = string(get(r, dst_col, ""));  isempty(dip) && continue
        occursin(r"^\d+\.\d+\.\d+\.\d+$", sip) || continue
        occursin(r"^\d+\.\d+\.\d+\.\d+$", dip) || continue

        push!(rows, (
            src_ip      = sip,
            dst_ip      = dip,
            src_port    = _int(r, sp_col, 0),
            dst_port    = _int(r, dp_col, 0),
            protocol    = _normalize_proto(_str(r, pr_col)),
            bytes       = _int(r, by_col, 64),
            packets     = _int(r, pk_col, 1),
            ts          = isnothing(ts_col) ? t : _int(r, ts_col, t),
            duration_ms = _int(r, du_col, 0)
        ))
    end
    isempty(rows) && error("No valid IPv4 flow rows found in $path")

    return _assign_host_ids(DataFrame(rows))
end

# ── internal helpers ──────────────────────────────────────────────────────────

function _find_col(df::DataFrame, candidates::Vector{String})::Union{Symbol,Nothing}
    cols = lowercase.(string.(names(df)))
    for c in candidates
        idx = findfirst(==(lowercase(c)), cols)
        isnothing(idx) || return names(df)[idx]
    end
    return nothing
end

_str(r, col)      = isnothing(col) ? "" : string(get(r, col, ""))
_float(r, col, d) = isnothing(col) ? Float64(d) : tryparse(Float64, string(get(r, col, d))) |> x -> isnothing(x) ? Float64(d) : x
_int(r, col, d)   = isnothing(col) ? d : let v = tryparse(Int, string(get(r, col, d))); isnothing(v) ? d : v end

function _normalize_proto(s::String)::String
    u = uppercase(strip(s))
    u == "6"   && return "TCP"
    u == "17"  && return "UDP"
    u == "1"   && return "ICMP"
    u in ("TCP","UDP","ICMP") && return u
    return "OTHER"
end

"""
    _assign_host_ids(flows) -> (flows_with_ids::DataFrame, hosts::DataFrame)

Build host table from unique IPs in flows. Assign integer host_id to each IP.
Adds src_id and dst_id columns to flows.
"""
function _assign_host_ids(flows::DataFrame)::Tuple{DataFrame, DataFrame}
    all_ips = unique(vcat(flows.src_ip, flows.dst_ip))
    sort!(all_ips)
    ip_to_id = Dict(ip => i for (i, ip) in enumerate(all_ips))

    flows.src_id = [ip_to_id[ip] for ip in flows.src_ip]
    flows.dst_id = [ip_to_id[ip] for ip in flows.dst_ip]

    # ensure required columns exist with defaults
    hasproperty(flows, :packets)     || (flows.packets     = ones(Int, nrow(flows)))
    hasproperty(flows, :duration_ms) || (flows.duration_ms = zeros(Int, nrow(flows)))
    hasproperty(flows, :ts)          || (flows.ts          = 1:nrow(flows))

    # host table — no ground truth (latent_vlan = 0 = unknown)
    hosts = DataFrame(
        host_id     = 1:length(all_ips),
        ip          = all_ips,
        subnet      = [join(split(ip, ".")[1:3], ".") * ".0/24" for ip in all_ips],
        latent_vlan = zeros(Int, length(all_ips)),
        vlan_name   = fill("unknown", length(all_ips))
    )

    return flows, hosts
end
